config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'download'=> 'static_pages#download'
  get     'faq'     => 'static_pages#faq'
  get     'download_tool'=> 'static_pages#download_tool'
  get     'signup'  => 'users#new'
  get     'login'   => 'sessions#new'
  get     'thanks'  => 'static_pages#thanks'
  post    'login'   => 'sessions#create'
  post    'hook'    => 'users#hook'
  delete  'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :messages, only: [:new, :create]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:download]
  #before_action :purshase_completed, only: [:download]
  
  def home
  end

  def help
  end
  
  def about
  end
  
  def download
  end
  
  def faq
  end
  
  def thanks
    flash.now[:info] = "Thank you for your purshase "
    render 'home'
  end
    
  def download_tool
    response.headers['Content-Length'] = File.size("#{Rails.root}/private/#{params[:id]}").to_s
    send_file("#{Rails.root}/private/#{params[:id]}",
              :filename => "#{params[:id]}",
              :type => "application/zip",
              :x_sendfile => true)
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="sub-container">
  <div class="page-header">
    <h1>About Me</h1>
  </div>
  <p>
    <h2>Maybe i'm a bot</h2>
  </p>
</div>

app/views/static_pages/download.html.erb
<% provide(:title, "Download") %>
<h1 class="text-center">Download</h1>
<h3>Download can be slow to start. You should right click on the link and save as... Download will start immediatly </h3>
<div class="row">
  <div class="col-md-12 text-center">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="text-center">
            Windows
          </th>
          <th class="text-center">
            OSX
          </th>
          <th class="text-center">
            Release
          </th>
        </tr>
      </thead>
      <tr>
        <td>
          <%=link_to "Download x64", download_tool_path(:id => "bot-win32-x64.zip") %>
          &nbsp
          &nbsp
          &nbsp
          &nbsp
          <%=link_to "Download x84", download_tool_path(:id => "bot-win32-ia32.zip") %>
        </td>
        <td>
          <%=link_to "Download x64", download_tool_path(:id => "bot-darwin-x64.zip") %>
        </td>
        <td>
          Version 1
        </td>
      </tr>
    </table>
  </div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77858550-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/faq.html.erb
<% provide(:title, "FAQ") %>
<div class="sub-container">
  <div class="page-header text-center">
    <h1>FAQ</h1>
  </div>
    <p>
      <h2 style="font-weight:bold;"><u>I did not receive any mail. What can i do ?</u></h2>
      <h3>Sometimes mail can be detected as spam. Check you spam/junk mail.</h3>
    </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1 style="font-size:45px;" class="text-center">How does it work?</h1>
<div class="text-center">
 <h3>addition/edition of states/countries are called actions. Actions are made of steps.</h3>
 </br>
 <h3><u>Example: Action of edit state</u></h3>
 <h3><span style="color:#1798c1">step 1-</span> Salesforce connection</h3>
 <h3><span style="color:#1798c1">step 2-</span> Navigate to states and countries</h3>
 <h3><span style="color:#1798c1">step 3-</span> Search country related to the state to edit</h3>
 <h3><span style="color:#1798c1">step 4-</span> Edit the state</h3>
 <h3><span style="color:#1798c1">step 5-</span> Save changes</h3>
</div>
</br>
</br>

<h1 style="font-size:45px;" class="text-center">Instruction</h1>
<div class="text-center">
  <p>
    <h2><span style="color:#1798c1">1-</span> Choose the source sandbox</h2>
  </p>
  <p>
    <h2><span style="color:#1798c1">2-</span> Choose countries and states you want to add</h2>
  </p>
  <p>
    <h2><span style="color:#1798c1">3-</span> Same thing for countries and states to edit</h2>
  </p>
  <p>
    <h2><span style="color:#1798c1">4-</span> Choose your target sandbox</h2>
  </p>
  <p>
    <h2><span style="color:#1798c1">5-</span> Drink a coffee</h2>
  </p>
  <p>
    <h2><span style="color:#1798c1">6-</span> Check results</h2>
  </p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
  <div class="center jumbotron">

    <p style="margin-top:0px">Salesforce bot</p>
    <p> for</p>
    <p>states and countries</p>
    <div class="row">
      <% if !logged_in? %>
        <%=link_to "Get if for free!", signup_path, class: "btn btn-lg btn-primary"%>
      <% end %>
      <h3>
        A simple way to add and edit states and countries on salesforce.com platform
      </h3>
    </div>
    <div class="row" style="text-align: right;font-size: 20px;color:#1798c1">
     Available on Windows and OSX</br> For salesforce classic only*
    </div>
  </div>

  <div class="pitch">
    <p>
      Did you ever had to create hundred of countries and states on salesforce platform ?
    </p>
    <p>
      Needless to say how it's a pain in the ***
    </p>
    <p>
      This tool may help you save a lot of your precious time
    </p>
  </div>

  <hr class="featurette-border">

  <div class="row featurette-border">
    <div class="col-md-7 col-md-push-5">
      <div class="step">1
        <h2 class="featurette-heading">Choose sandbox on which you want retrieve states and countries</h2>
      </div>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <%= image_tag( "bot1.png", height: '375', width: '450', alt: "Rails logo") %>
    </div>
  </div>

  <hr class="featurette-border">


  <div class="row featurette">
    <div class="col-md-7">
      <div class="step">2</div>
      <h2 class="featurette-heading">Select states and countries to add</h2>
    </div>
    <div class="col-md-5">
      <%=image_tag( "bot2.png", height: '375', width: '450', alt: "Rails logo") %>
    </div>
  </div>

  <hr class="featurette-border">

  <div class="row featurette-border">
    <div class="col-md-7 col-md-push-5">
      <div class="step">3</div>
      <h2 class="featurette-heading">Select states and countries to edit</h2>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <%= image_tag( "bot3.png", height: '375', width: '450', alt: "Rails logo") %>
    </div>
  </div>

  <hr class="featurette-border">

  <div class="row featurette">
    <div class="col-md-7">
      <div class="step">4</div>
      <h2 class="featurette-heading">Choose sandbox on which you want to create states and countries</h2>
    </div>
    <div class="col-md-5">
      <%=image_tag( "bot4.png", height: '375', width: '450', alt: "Rails logo")%>
    </div>
  </div>

  <hr class="featurette-border">

  <div class="row featurette-border">
    <div class="col-md-7 col-md-push-5">
      <div class="step">5</div>
      <h2 class="featurette-heading">Track progress of each processes</h2>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <%=image_tag( "bot5.png", height: '375', width: '450', alt: "Rails logo") %>
    </div>
  </div>
  

  <hr class="featurette-border">

  <div class="row featurette">
    <div class="col-md-7">
      <div class="step">6</div>
      <h2 class="featurette-heading">Check results</h2>
    </div>
    <div class="col-md-5">
      <%=image_tag( "bot6.png", height: '375', width: '450', alt: "Rails logo")%>
    </div>
  </div>
  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  
    ga('create', 'UA-77858550-1', 'auto');
    ga('send', 'pageview');
  </script>