config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'download'=> 'static_pages#download'
  get     'faq'     => 'static_pages#faq'
  get     'download_tool'=> 'static_pages#download_tool'
  get     'signup'  => 'users#new'
  get     'login'   => 'sessions#new'
  get     'thanks'  => 'static_pages#thanks'
  post    'login'   => 'sessions#create'
  post    'hook'    => 'users#hook'
  delete  'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :messages, only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
Made by kokoweite
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
       <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "GitHub", 'https://github.com/kokoweite/sfdcbot' %></li>
      </ul>  
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Instruction", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Download", download_path %></li>
          <% if user_admin? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><%= link_to "FAQ", faq_path %></li>
        <li><%= link_to "Contact", new_message_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="sub-container">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{ message_type }") %>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>